### ISSUE TITLE
Don't get channels with a _

### ISSUE THREAD

**Issue by Dkamps18** [Feverqwe/twiMonBot#10]
For example if you enter the_jover it adds thejover

**Comment by Feverqwe** [comment]
fixed!

**Comment by Dkamps18** [comment]
He is still doing it :( 

https://prnt.sc/hpj3hw

**Comment by Feverqwe** [comment]
try enter channel url

**Comment by Dkamps18** [comment]
url doesn't work either https://prnt.sc/hpwqsx

**Comment by Feverqwe** [comment]
Oh, sorry, try now please.

**Comment by Dkamps18** [comment]
Its working now
