### ISSUE TITLE
Bot repeats the notification (error)

### ISSUE THREAD

**Issue by Blastbeater** [Feverqwe/twiMonBot#11]
Hello! Thank you very much for your bot.
I use it for about a year at my group and it never had any errors or problems. 
But recently I found out en error. After started the broadcast at the channel from the list - we recieved a notification at the group at the start of broadcast. And after broadcast ended, bot keeps sending notifications about same broadcast to the group. It sent us this notification every hour. 
I tried to delete the channel from the list and add it agian. I tried to stop bot and start it again. I cleared the list and added my channels there again. And nothing helps. It passed 4 days and bot keeps sending same notification to the group every hour. 
Ho can у solve this error?

**Comment by Feverqwe** [comment]
Hello! What channel on twitch are you talking about? I'm trying to reproduce this problems.

**Comment by Blastbeater** [comment]
Here's the link for the video: https://gaming.youtube.com/watch?v=FN0nFIGm0sI

For example, I recieve that message today at 13:15 than at 13:55 (Moscow time)

![ss 2018-07-23 at 02 10 41](https://user-images.githubusercontent.com/34507354/43073429-44a5832e-8e82-11e8-8853-dced61a4a9a7.jpg)
![ss 2018-07-23 at 02 10 46](https://user-images.githubusercontent.com/34507354/43073430-44d1182c-8e82-11e8-935f-3766d5173e23.jpg)

Screenshot of previous notification bug (first time it happened on July 19th):
![ss 2018-07-23 at 02 14 45](https://user-images.githubusercontent.com/34507354/43073581-d39f33fe-8e82-11e8-9a45-b8daa7530467.jpg)

**Comment by Feverqwe** [comment]
I see this problem. It is youtube api bug. Sometimes api response stream as live and bot send message to user. I think how to fix it. I wrote about it in youtube support.

**Comment by Feverqwe** [comment]
I add check for live for a videos, I think it help until bug not fixed.

**Comment by Blastbeater** [comment]
Thank you! 
I changed twiMonbot to ytWatchBot and I see that ytWatchBot is more suitable for our group. And it works fine. 
Anyway thank you for your job. I hope my bug report will be helpful for twiMonbot users in future and will make it a little bit better!

Have a good day!
Cheers.
