### ISSUE TITLE
wasd.tv support

### ISSUE THREAD

**Issue by Evgeny-** [Feverqwe/twiMonBot#16]
Since Russia gonna have their own Cheburnet in the current year, i think it will be useful to add new russian streaming website.

**Comment by Evgeny-** [comment]
Есть даже какое-то не публичное апи 

https://wasd.tv/api/media-containers?media_container_status=RUNNING&limit=100&offset=0&media_container_type=SINGLE,COOP

Я думаю надо спросить у них

**Comment by Feverqwe** [comment]
Да, я посмотрел есть апи, вполне рабочий. Но этот сайт не доступен с бекенда бота как и goodgame т.к. DO заблокирован. Чет особо желание от этого добавлять его нет, хотя для гг есть обход блокировок, но это так не приятно все...

**Comment by Evgeny-** [comment]
Я думаю что это не большая проблема поднять проксю, или купить готовую или использовать имеющиеся. Пару строк к коду и немного затрат.

**Comment by Evgeny-** [comment]
Но вообще я согласен, вероятность что сервис (васд) взлетит примерно нулевой, поэтому таким заниматься, пожалуй, не интересно.

**Comment by Feverqwe** [comment]
Ну ок, я сделал имплементацию, тестово запущу, если что потом удалю, делов то..  еще не ясна как со стабильностью там... 3d4a93da1d9e055667d7bc65277c7f293a9b2248

**Comment by Evgeny-** [comment]
>Oops! Channel https://wasd.tv/channel/22196/ (Wasd) can not be found!
Пока что так, держу в курсе.

**Comment by Evgeny-** [comment]
А, это говно вообще лежит. Видимо они тоже на DO хостятся, за пять долларов. Или на юкозе.

**Comment by Feverqwe** [comment]
Да, на момент написания кода оно работало, а теперь все лежит и даже если где то проблема, то поправить не получится

**Comment by Feverqwe** [comment]
Вроде починил, но это не точно.

**Comment by Evgeny-** [comment]
За 10-20 секунд добавилось :) 

И все ради одного канала

**Comment by Feverqwe** [comment]
удалено

**Comment by ovgamesdev** [comment]
Api теперь публичен

**Comment by Feverqwe** [comment]
> Api теперь публичен

пока не вижу смысла использовать, т.к. он основан на алиасах а не на id пользователе. Пока работает то что есть - пусть работает.
Если мы говорим об это апи
```
GET api/v2/broadcasts/public?channel_name={Алиас стримера}
```

**Comment by ovgamesdev** [comment]
> > Api теперь публичен
> 
> Добрый день. С этого момента можно поподробнее? Что значит "публичен"? Васд где-то доки выложил?

Документация слабая, но есть
https://wasd.tv/faq/dev
