### ISSUE TITLE
Telegram message does not contain link to Youtube Stream

### ISSUE THREAD

**Issue by lespaul1488** [Feverqwe/twiMonBot#18]
After the latest changes, the telegram message with started stream contains the only link to the channel, but not to an ongoing stream. 

<img width="274" alt="Screenshot 2019-08-19 at 10 37 05" src="https://user-images.githubusercontent.com/6555305/63247453-c0993280-c26d-11e9-9a7b-9c06a8901271.png">

At Jul 25 link to the video where there 
<img width="502" alt="Screenshot 2019-08-19 at 10 42 12" src="https://user-images.githubusercontent.com/6555305/63247584-11109000-c26e-11e9-8635-9f63b22dd30a.png">

**Comment by Feverqwe** [comment]
Fixed b9bcb4f48b784d5c83b74ca2fefa64f810efedd4

**Comment by lespaul1488** [comment]
Works! Thanks a lot!
