### ISSUE TITLE
Wrong Twitch channel

### ISSUE THREAD

**Issue by albertorossi993** [Feverqwe/twiMonBot#29]
If I add the Twitch channel "playapex" it adds me a channel named "playapex_".  Even if I put the link of the right channel it always gives me the one with the final dash

**Comment by albertorossi993** [comment]
https://user-images.githubusercontent.com/83984103/117723789-21576400-b1e3-11eb-9a82-d4ead629dcc6.mp4

**Comment by Feverqwe** [comment]
Fixed
