### ISSUE TITLE
Clone Heroku

### ISSUE THREAD

**Issue by c3bola** [Feverqwe/twiMonBot#31]
I would like to clone the bot into heroku so I can implement some new functions

- choose which game should be notified
- only admin can add channels (bot in groups)

is it possible to do that?

This is an example
https://heroku.com/deploy?template=https://github.com/jacklul/inlinegamesbot/tree/develop

**Comment by Feverqwe** [comment]
You can fork it and do what you want. I never use heroku, but I think it possible.
