### ISSUE TITLE
In a group: when someone uses a command that requires a reply, it gets stuck in reply state

### ISSUE THREAD

**Issue by AlwaysMoreHats** [Feverqwe/twiMonBot#37]
Using Telegram Desktop for Mac
Telegram version 8.5 (226935)

Every time I go to the channel, I get this prompt
![image](https://user-images.githubusercontent.com/1030358/152075275-9858310b-06db-4908-84ba-4914734b1f64.png)

Deleting the message is a workaround but it's annoying that it happens at all

**Comment by Feverqwe** [comment]
Add some changes, may be will be better.

https://github.com/Feverqwe/twiMonBot/commit/d17572ea3e1c533263fdeaf7771d507dff078f2d
