### ISSUE TITLE
Channel could not be found (YouTube)

### ISSUE THREAD

**Issue by S-ed** [Feverqwe/twiMonBot#7]
Not sure why this channel could not be found:

![screenshot 1502823692](https://user-images.githubusercontent.com/3008353/29331566-8a59575e-8205-11e7-9eb1-1fe8b6c66c46.png)

http://www.youtube.com/channel/UCXPnfpikLeCQAzweo3-OSuw

**Comment by Feverqwe** [comment]
Yes. Need to change message. Bot don't add channels without completed\live\upcoming broadcasts.

**Comment by bpo5r5** [comment]
@Feverqwe sorry for the necro-bump, but I'm also having the same issue with the following channel
https://www.youtube.com/channel/UCtr0rV8VUtacwq3aoOi4FLA

Any ideas?

**Comment by Feverqwe** [comment]
Same problem. I'am add error message about it.

**Comment by bpo5r5** [comment]
I'm using your project here: https://github.com/Feverqwe/ytWatchBot; it works a lot better and has 0 problems adding channel URLs 👍

**Comment by Feverqwe** [comment]
twiMonBot for live streams, ytWatchBot for added videos.

**Comment by bpo5r5** [comment]
@Feverqwe OH! That make's a lot more sense. Sorry 😓

Also, does it use YouTube Push Notifications for new videos, or does it check it periodically?

**Comment by Feverqwe** [comment]
twiMonBot use push and periodically check, cause youtube don't always send push.  
ytWatchBot use push for revieve channel changes and then use activity api, and time after time do full check.
